.gitignore
digital_asset_types/src/dao/generated/asset_data.rs
migration/src/lib.rs
migration/src/m20230508_142103_add_offchain_reindex.rs
nft_ingester/src/program_transformers/bubblegum/mint_v1.rs
nft_ingester/src/program_transformers/token_metadata/v1_asset.rs
nft_ingester/src/tasks/common/mod.rs
tests/bgtask_creator/src/main.rs

This adds an offchain reindexer parameter that allows to trigger reindexing  without updating the stored metadata json.

Add offchain reindex parameter

---

nft_ingester/src/program_transformers/token_metadata/v1_asset.rs

Fixes a token account asset linking bug. If there were multiple entries in the `token_accounts` table then the wrong owner could be loaded and pushed to the `asset` table.

Fixes token owner bug

---

digital_asset_types/tests/common.rs
digital_asset_types/tests/json_parsing.rs
tests/tree-status/src/main.rs

Compare maximum seq number per each leaf with assets table in database
example:
```
Running `target/debug/tree-status --rpc {RPC} check-tree-leafs -p {POSTGRES} -t 8wKvdzBu2kEG5T3maJBX8m2gLs4XFavXzCKiZcGVeS8T`
checking tree leafs 8wKvdzBu2kEG5T3maJBX8m2gLs4XFavXzCKiZcGVeS8T
b6f35ce4a304f88a74966628420d8a965a19c7e02af9f350dd8fe16c91d4bc70 247: not found in db, seq 248
0000000000000000000000000000000000000000000000000000000000000000 0: not found in db, seq 0
d6f9e2cea59a9a3a1927a734bc28be0bfacc725fe36faac712aeb3a0ab2db068 525: not found in db, seq 526
```

add check-tree-leaf to tree-status

---

Cargo.lock
nft_ingester/Cargo.toml
nft_ingester/src/backfiller.rs
nft_ingester/src/bin/fetch-trees.rs
nft_ingester/src/config.rs
nft_ingester/src/main.rs

Closes #32 
I added option `backfiller_trees` (`Option<Vec<String>>`) to the config. If any tree is specified all other trees would be removed from finder result.
@linuskendall can we check it somehow before merging? I added extra logs, so it would be possible to see how many trees left after every filter.
```
info!("Number of Trees to backfill (with failed/locked filter): {}", all_trees.len());
```
- all trees received from getPA
- trees left after filter with `backfiller_trees`
- after removing all failed/locked in `backfill_items`
- after removing existed in `cl_items`

check only specified trees with backfiller

---

tests/txn_forwarder/src/main.rs

should help with issue https://github.com/rpcpool/rpcpool/issues/3826

tests tools: ignore invalid signatures in txn fwrd

---

Cargo.lock
Cargo.toml
tests/acc_forwarder/src/main.rs
tests/tree-status/src/main.rs
tests/txn_forwarder/src/lib.rs
tests/txn_forwarder/src/main.rs

Allow to pass custom header to our patched validator :wink: 
I needed to patch `solana-client` for custom header support.
Plus added retries for `getSFA`.

tests tools: support custom header

---

das_api/src/api/api_impl.rs
das_api/src/api/mod.rs
digital_asset_types/src/dao/mod.rs
digital_asset_types/src/dao/scopes/asset.rs

* add dto parameter
* add dao condition
* upd asset_data fetching to ensure single presence of asset_data in query
* use asset.asset_data key for linking between asset/asset_data
* fix: breaking arg order for array queries
* chore: consistent arg order in `SearchAssets` destructuring
* fix: breaking arg count for array params in searchAssets

feat(das-api): support searching assets by `jsonUri` parameter (#79)

---

das_api/src/api/api_impl.rs

[Fix before/after cursors](https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/commit/f25e468a7007f03c6a9f5a52e45daf2ceb6b2b73)

Fix before/after cursors. (#67)

---

nft_ingester/src/backfiller.rs

The `fetch_trees_by_gpa` called used to gather up trees on-chain that need to be included in the DAS index exits returning an error if there is any issues deserializing any of the queried trees. The error prevents any trees any of the discovered tree from being included in the backfill.
```
Failed to get size of max depth 12 and max buffer size 32                                                                                                                                                                                                                                                             [36/18983]
{"timestamp":"2023-12-01T14:42:04.061547Z","level":"ERROR","fields":{"message":"Failed to get size: AnchorError { error_name: \"ConcurrentMerkleTreeConstantsError\", error_code_number: …
```

Stop Bad Trees from Exiting Backfiller Tree Lookup

---

digital_asset_types/src/dao/generated/tree_transactions.rs
migration/src/m20231208_103949_create_tree_transactions_table.rs
tree_backfiller/README.md
tree_backfiller/src/backfiller.rs
tree_backfiller/src/metrics.rs
tree_backfiller/src/queue.rs
tree_backfiller/src/tree.rs

- Fast forwarding never finding the latest signature because of signature transform failures
- Program not exiting from worker handlers not resolving

Tree backfiller patches

---

tree_backfiller/src/backfiller.rs
tree_backfiller/src/queue.rs
tree_backfiller/src/tree.rs

- Use a pool of messengers instead of a channel for funneling all messages to a single messenger instance.
- Interact with the db for a transaction in a worker thread instead of the main tree crawl thread.
- Fix acquiring a messenger from the queue and returning it.
- Add extra argument to pass a list of trees that should be crawled. If not set crawl all trees.

Crawl Select Trees and Concurrency Improvements

---

nft_ingester/src/program_transformers/bubblegum/db.rs
nft_ingester/src/program_transformers/bubblegum/mod.rs
tree_backfiller/src/backfiller.rs
tree_backfiller/src/rpc.rs
tree_backfiller/src/tree.rs

- Remove the use of tree_transactions to assist in backfilling but similar info is available on cl_items and cl_audits (if enabled).

Remove use of tree_transactions from the backfiller

---

tree_backfiller/src/backfiller.rs
tree_backfiller/src/rpc.rs
tree_backfiller/src/tree.rs

- Identify missing gaps in tree sequences.
- Add worker to process gaps in a thread.

[Tree Backfiller] Gap Filling

---

nft_ingester/src/program_transformers/bubblegum/db.rs

- Ingestion slowed to a snail after release reintroduced the insertion of backfill items.
- The select used was causing accessshare and excluselocks to be taken out on the table which prevents ingestion handlers from completing.
- Remove the insertion of the record since cl_audits_v2 is used now instead of it for tree backfilling.

Remove insert of backfill item

---

integration_tests/tests/integration_tests/common.rs
metadata_json/src/cmds/mod.rs
metadata_json/src/cmds/single.rs
metadata_json/src/main.rs
metadata_json/src/worker.rs

- Add subcommand to das-metadata-json to index immediately in the main thread a metadata json by its mint
- Remove the host from the metrics. The hosts vary too much to be used for metrics reporting.

[DAS Metadata JSON] Single Command

---

ops/src/bubblegum/audit.rs
ops/src/bubblegum/cmd.rs
ops/src/bubblegum/mod.rs
ops/src/bubblegum/tree.rs

Issue
The backfiller was not filtering out failed transactions before pushing them for indexing which caused incorrect information to be indexed.
Fix
Add filter to remove failed transactions before pushing along to ingester.
Changes
Add audit command to ops bubblegum to identify failed transaction that made it into the index

[Patch] Filter out failed transactions while tree backfilling #175

---

nft_ingester/src/program_transformers/bubblegum/db.rs
ops/src/bubblegum/audit.rs

- Pass optional fix flag to delete cl_audits_v2 transfers
- Switch to saving the id of the cl_audits_v2 in the log file so can support picking continuing when restarted
- Optionally run on a selected list of trees

[Das Ops] Add fix option to bubblegum audit

---

das_api/src/api/api_impl.rs
das_api/src/config.rs

- Add max_database_connections to read api with default being previous value of 250.

Config Max DB Connections

---

nft_ingester/src/program_transformers/token_metadata/v1_asset.rs

- Disable retries to test affect on ingestion rate when there is a backlog of messages in the queue.

No retries when looking up owner and token

---

backfill/src/worker/tree.rs
blockbuster/src/lib.rs
tools/acc_forwarder/src/main.rs

This PR introduces a new `force` flag to the `TreeWorkerArgs` struct, allowing for a complete reindex of trees from the first transaction up to the current sequence number. When the force flag is set, the backfiller skips checking gaps in `cl_audits_v2`, effectively ignoring existing audit data and performing a full reindex.
- Added a `force` boolean flag to `TreeWorkerArgs` struct
- Modified the `start` method in `TreeWorkerArgs` to use the force flag
- Removed queries to `cl_audits_v2` when force flag is set
This change allows for a complete reindex of trees.
- The main logic change is in the `start` method of `TreeWorkerArgs`
- Pay attention to the handling of gaps when the force flag is set vs. when it's not
- Ensure that the existing functionality is preserved when the force flag is …

Add force flag to TreeWorkerArgs for complete reindexing

---

program_transformers/src/bubblegum/db.rs

Remove seq check on cl_items so that the backfiller go rebuild them.
If the backfiller is running while the ingester is processing fresh entries if a asset is mutated the proof will be reset by the backfiller until it replays that record.
This procedure is best to do while the transaction ingester is not running.

Allow Proof Reindexing

---

backfill/src/worker/program_transformer.rs
program_transformers/src/lib.rs

Though transactions where ordered by slot there can be many transactions that change a tree in a slot. When indexing instructions must be written in order based on the seq associated to the tree change.
- Pull instructions from the gathered transactions, run them through blockbuster to get access to seq change for the tree, order instructions by seq, and then write them to the database.
```
tree: Dgs9FMfuCWVg7zSzymEwJ7FJStKzpLEYpERTbP13shdQ
local Valid Proofs: 423 / 423
Command failed.====================] 100% | ETA: 0s | 423/423
```

Respect Seq When Bubblegum Backfilling

---

grpc-ingest/src/grpc.rs

Issue : GRPc stops pushing messages to redis but does not crash.

fix: keep grpc alive by sending using ping-pong

---

grpc-ingest/src/config.rs
grpc-ingest/src/ingester.rs
grpc-ingest/src/redis.rs

- When stream starts delete and recreate the consumer so pending messages is reset. By doing this you don't need to track pending messages and use xread starting from 0.

Reset Redis Consumer

---

grpc-ingest/src/ingester.rs
grpc-ingest/src/prom.rs
grpc-ingest/src/redis.rs

Though message were being read from redis a large amount were lost when passed to the dynamic version of the handler. This would leave messages as pending, not be processed, and never acknowledged.
- Trait MessageHandler for model different variants of handling a redis message from any stream
- Implement AccountHandle, TransactionHandle, DownloadMetadataJsonHandle
- Adjust shutdown code to be able to wait for jobs and shutdown cleanly

Fix Messages Dropped By Handler

---

grpc-ingest/config-ingester.yml
grpc-ingest/src/grpc.rs
grpc-ingest/src/ingester.rs
grpc-ingest/src/prom.rs
grpc-ingest/src/redis.rs

The ingester reads messages far faster than they can be xack and xdel by redis. As the ingester run the executor gets overwhelmed with messages which cause it to slow down as more messages accumulate in its buffer.
- Only read another page of messages if the ack channel has capacity
- Track all tasks grc and ack

Back Pressure XRead

---

grpc-ingest/config-ingester.yml
grpc-ingest/src/grpc.rs
grpc-ingest/src/ingester.rs
grpc-ingest/src/redis.rs

Even though reads are being throttled based on capacity of the ack channel overtime the injector queue builds to the point where performance drops on program_transformer tasks.
- Use semaphore to ensure jobs only scheduled if there is capacity this should ensure the crossbeam injector queue doesn't grow over time.

Backpressure Ingest Process Tasks

---

grpc-ingest/src/ingester.rs
grpc-ingest/src/redis.rs

- Remove throttle based on ack capacity on ingest tasks and instead just use the semaphore that is tracking number of running tasks.
- Fix metrics tracking xread for metrics. It was posting to xack.

Remove Ack Throttle on Tasks

---

grpc-ingest/src/config.rs
grpc-ingest/src/postgres.rs

- Config of ingester supports setting idle and max lifetime

Configure database idle and max lifetime

---

bubblegum/src/lib.rs
bubblegum/src/verify.rs
grpc-ingest/src/monitor.rs
grpc-ingest/src/prom.rs
ops/src/bubblegum/verify.rs

- 🚀 send reports as they come over a channel
- 🐛 register bubblegum promo metrics

Send proof reports as they complete

---

grpc-ingest/config-ingester.yml
grpc-ingest/src/config.rs
grpc-ingest/src/redis.rs
prometheus-config.yaml

- Keep an in memory buffer of redis messages coming in from redis there is no delay in workers processing the next message even if all the workers are busy.

Buffer Redis Messages

---

grpc-ingest/config-ingester.yml
grpc-ingest/src/redis.rs

- Always create the stream consumer group. Recreate the consumer based on its configured named in the config.

Recreate consumer but not groups

---

grpc-ingest/src/prom.rs
grpc-ingest/src/redis.rs

- Histogram prom timing for ingest job times

Time Ingest jobs

---

program_transformers/src/bubblegum/burn.rs
program_transformers/src/bubblegum/cancel_redeem.rs
program_transformers/src/bubblegum/collection_verification.rs
program_transformers/src/bubblegum/creator_verification.rs
program_transformers/src/bubblegum/delegate.rs
program_transformers/src/bubblegum/mint_v1.rs
program_transformers/src/bubblegum/redeem.rs
program_transformers/src/bubblegum/transfer.rs
program_transformers/src/bubblegum/update_metadata.rs
program_transformers/src/token_metadata/v1_asset.rs

- Write the cli items in the transaction being taken out for the asset so each cl item isn't a round trip.
Locally P90 before is 9 sec and after 1 sec

Wite CL Items in the transactions

---

program_transformers/src/asset_upserts.rs
program_transformers/src/token/mod.rs
program_transformers/src/token_metadata/master_edition.rs
program_transformers/src/token_metadata/v1_asset.rs

Context
While observing postgres logs I saw the same record (a collection mint) being updated over and over again from be referenced in bubblegum mint instructions. The fields aren't different on the asset but its slot is updating. When the update happens the row is locked because it has to update indexes. This causes other processes to wait to do the same thing causing a major bottleneck.
Change
Expand the where clause on the update to only update the record when the slot is larger and any of the fields have changed.

Only update the record when fields have changed for token and metadata programs

---

grpc-ingest/src/grpc.rs

Allow operator to set commitment level on their subscriptions.

Respect commitment level set in grpc config (#191)

---

program_transformers/src/bubblegum/db.rs

- Switch to writing cl items in batch to eliminate round trips and allow postgres to plan given all the info
```
digital-asset-rpc-infrastructure-db-1     | 2024-12-19 22:21:32.756 UTC [61347] LOG:  execute sqlx_s_6: INSERT INTO "cl_items" ("tree", "node_idx", "leaf_idx", "seq", "level", "hash") VALUES ($1, $2, $3, $4, $5, $6), ($7, $8, $9, $10, $11, $12), ($13,
$14, $15, $16, $17, $18), ($19, $20, $21, $22, $23, $24), ($25, $26, $27, $28, $29, $30), ($31, $32, $33, $34, $35, $36), ($37, $38, $39, $40, $41, $42), ($43, $44, $45, $46, $47, $48), ($49, $50, $51, $52, $53, $54), ($55, $56, $57, $58, $59, $60), ($
61, $62, $63, $64, $65, $66), ($67, $68, $69, $70, $71, $72), ($73, $74, $75, $76, $77, $78), ($79, $80, $81, $82, $83, $84), ($85, $86, $87, $88, $89, $90) ON CONFLICT ("tree", …
```

Write cl items in a batch

---

program_transformers/src/bubblegum/mint_v1.rs
program_transformers/src/bubblegum/transfer.rs
program_transformers/src/mpl_core_program/v1_asset.rs
program_transformers/src/token/mod.rs
program_transformers/src/token_metadata/v1_asset.rs

- asset indexing timeout from 5s to 1s
- All token account have timeout of 100ms
- Bubblegum mint_v1 to 2s

Stricter Lock Timeouts

---

Api.Dockerfile
Builder.Dockerfile
Ingest.Dockerfile
Load.Dockerfile
Migrator.Dockerfile
Proxy.Dockerfile

fix rust  docker versions to 1.83

fix docker versions to 1.83

---

grpc-ingest/src/grpc.rs

Context
The snapshot service closes the stream when its done transmitting all messages but the grcp2redis command don't handle the condition and remains running when it should shutdown.
Outcomes
When stream closes gracefully terminate the command

Shutdown program on stream error or close

---

docker-compose.yaml

By default set to log queries slower than 50ms

Add auto_explain to postgres to log slow db query plans

---

das_api/src/api/mod.rs
das_api/src/main.rs

add temp warn logs for params to debug query params issue

add params warn logs

---

grpc-ingest/config-ingester.example.yml
grpc-ingest/src/config.rs
grpc-ingest/src/ingester.rs

Use redis pipes to write x_add commands of metadata_json download data  and flush the pipe at regular intervals

add redis pipes for processing metadata download

---

dash

- Script to replicate and evaluate Asset not found errors returned from api logs.
```bash
cat id-list.txt | ./dash asset index-e {rcp-endpoint} -d {database-url}
cat id-list.txt | ./dash asset get -e {rcp-endpoint}
```
Script expects debug build of ops cli and script should be ran from the root of directory of the repository

Script for debugging asset not found

---

bubblegum/src/backfill/gap.rs
bubblegum/src/backfill/worker/gap.rs
bubblegum/src/backfill/worker/tree.rs
core/src/solana_rpc.rs

Add overfetch to fix the issue where small gaps are not filled in the backfill process due to empty `get_signatures_for_address` RPC responses

`feat:` Add over-fetch for small gaps on backfilling

---

migration/src/lib.rs
migration/src/m20250313_095336_drop_idx_token_accounts_owner_and_idx_ta_mint.rs
migration/src/m20250313_095449_add_idx_ta_owner_amount_and_idx_ta_mint_amount.rs

getTokenAccounts calls were kind of slow as we have amount > 0 condition , adding a composite index (owner,amount) can fix this potentially and reduce the latency
@kespinola let me know if we want to add amount_greater_than or amount_less_than filters here

`impr` : add composite index (owner,amount) and (mint,amount) on token_accounts table

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/db.rs
core/src/solana_rpc.rs
integration_tests/Cargo.toml
integration_tests/tests/integration_tests/main.rs
integration_tests/tests/integration_tests/ops_purge.rs
ops/Cargo.toml
ops/src/lib.rs
ops/src/main.rs
ops/src/purge/cmd.rs
ops/src/purge/mod.rs
ops/src/purge/purger.rs

`feat` : Add cmd for purging token_accounts and mints which dont exists on chain

---

digital_asset_types/src/dao/mod.rs
integration_tests/tests/integration_tests/show_collection_metadata_option_tests.rs
integration_tests/tests/integration_tests/snapshots/integration_tests__fungibles_and_token_extensions_tests__fungible_token_get_asset_scenario_1.snap
integration_tests/tests/integration_tests/snapshots/integration_tests__fungibles_and_token_extensions_tests__token_extensions_get_asset_scenario_1.snap
integration_tests/tests/integration_tests/snapshots/integration_tests__regular_nft_tests__reg_get_asset_batch-only-2.snap
integration_tests/tests/integration_tests/snapshots/integration_tests__show_collection_metadata_option_tests__get_asset_with_show_collection_metadata_option.snap

Avoid seq scan for TokenType::Fungible case , update ownerType  filters and conditions
`Note` : when using TokenType::All along with ownerAddress, due to nature of the query db performs a seq scan though we have setup indexes for that  , This can be fixed by using `Unions` ( query on asset table union  query on asset table and left join with token_accounts table). In order to use unions we need to restructure the code and handle this case explicitly

`fix` : searchAsset query with tokenType, ownerType filters

---

digital_asset_types/src/dao/mod.rs

- On Eclipse we have token accounts that aren't close but assigned to the user. This lead to search finding mints that they don't actually own but have the account. Only return the asset if the amount held i the TA is greater than 0.

Drop amount zero tokens from search all
