tests/txn_forwarder/src/main.rs
=> Tx multitask patch

tests/tree-status/Cargo.lock, tests/tree-status/Cargo.toml, tests/tree-status/src/main.rs
WIP: Adding parameters to the test script check-tree
=> Parameters

tests/tree-status/Cargo.lock, tests/tree-status/Cargo.toml, tests/tree-status/src/main.rs
Adds support to the tree-status tool to show missing sequence numbers.
=> Add missing seq

digital_asset_types/src/dapi/common/asset.rs
Fixes panics on unwrapping of mime type data.
=> Hotfix for asset panic

tests/txn_forwarder/Cargo.lock, tests/txn_forwarder/Cargo.toml, tests/txn_forwarder/src/main.rs, tests/txn_forwarder/src/utils.rs
Adds improvements to txn forwarder to support retries.
=> Updated txn forwarder

tests/bgtask_creator/src/main.rs
Adds further CLI args to the bgtask creator.
=> Adds further cli args to bgtask creator

digital_asset_types/src/dapi/common/asset.rs
A first hotfix to address some files parsing issues.
=> Hotfix: Files fixes

digital_asset_types/src/dapi/change_logs.rs
adds a fix for getAssetProof from Helius labs
=> fix(das-api): fix getAssetProof

tests/tree-status/src/main.rs
```
Running `target/debug/tree-status --rpc '...' show-tree -t 8wKvdzBu2kEG5T3maJBX8m2gLs4XFavXzCKiZcGVeS8T`
showing tree 8wKvdzBu2kEG5T3maJBX8m2gLs4XFavXzCKiZcGVeS8T
743 247 4ugEuwxgZ8BpWaaZGDPWhdcpG2dBEUVFxjcgGzjHGHC4QJ6zKABUQzj3BfxM9XeX2MFCJa3fEmkByUsH46txxM7n 13
742 741 3ieuLcyk82VC9yVX2ekT5eBi5vCStNrt9czKDrsSbEeEXdcdbC5oNrQA5xCNHnStHQezonSenZVQEUhRn2LsVccL 116
741 740 2WocPF7XwjgfJEu2U3rFqBroVd5cRkjsBiUaYJerjVWyCtdPGvLwsMrKzcWfBfAR8c5t3k5uJ2kTPvchWdQ5nZBY 121
740 739 5qkfozmjDxHprDf8ZiTRGRyysWfrUt3oZDLL5yTkAV6KHNDxzbYWSfmVmJLUZhmLLhcw57VbnkYpd93wGaYqZEJw 122
```
`sequence leaf_idx signature signature_id`
=> add leaf_idx to tree-status/show-tree

tests/tree-status/src/main.rs
Adds tx signature to the output of tree-status.
=> Adds tx signature to tree-status output

Cargo.lock, tests/acc_forwarder/Cargo.toml, tests/acc_forwarder/src/main.rs, tests/tree-status/Cargo.toml, tests/tree-status/src/main.rs, tests/txn_forwarder/Cargo.toml, tests/txn_forwarder/src/lib.rs, tests/txn_forwarder/src/main.rs
=> txn_forwarder: add read_lines to lib

nft_ingester/src/program_transformers/bubblegum/db.rs
=> Fix issue in the cl_items insert

nft_ingester/src/program_transformers/bubblegum/db.rs
=> Bugfix cl items

.github/workflows/test.yml, rust-toolchain.toml
Changes runners to github public ones.
=> Fix builds

tests/acc_forwarder/src/main.rs
=> Don't quite on failed fetch

tests/acc_forwarder/src/main.rs, tests/tree-status/src/main.rs, tests/txn_forwarder/src/main.rs
Move tools to using finalized.
=> Move to using finalized

tests/acc_forwarder/src/main.rs, tests/tree-status/src/main.rs, tests/txn_forwarder/src/lib.rs, tests/txn_forwarder/src/main.rs
Fixes bug in tree status command, transaction fetching.
=> Fix tree status

tests/acc_forwarder/src/main.rs, tests/tree-status/src/main.rs
=> tests tools: do not process failed transactions

tests/tree-status/src/main.rs
Add `tree_status_missing_seq` to `tree-status`.
https://github.com/rpcpool/digital-asset-rpc-infrastructure/pull/49#discussion_r1209682080
=> tests tools: more metrics in tree-status

digital_asset_types/src/dapi/common/asset.rs, digital_asset_types/src/rpc/asset.rs
Fixing edition nonce to be null if not present.
=> Fix edition nonce

digital_asset_types/src/dapi/common/asset.rs, tests/txn_forwarder/src/main.rs
=> txn_forwarder: add tree to metrics

tests/acc_forwarder/src/main.rs, tests/tree-status/src/main.rs, tests/txn_forwarder/src/lib.rs, tests/txn_forwarder/src/main.rs
Adds group fields to prom metrics. Fixes #61 .
=> Adds group field to prometheus metrics

tests/tree-status/src/main.rs, tests/txn_forwarder/src/lib.rs
=> tests tools: add concurrency for check-trees-leafs

nft_ingester/src/program_transformers/bubblegum/db.rs
Temporarily disabling cl audits, for performance concerns.
=> Disable cl audits

digital_asset_types/src/dao/scopes/asset.rs
Adds ordering to creator position to api responses.
=> Order by creator position

das_api/src/api/api_impl.rs, das_api/src/api/mod.rs
=> fix: make delegate string (#73)

nft_ingester/src/program_transformers/bubblegum/burn.rs, nft_ingester/src/program_transformers/bubblegum/cancel_redeem.rs, nft_ingester/src/program_transformers/bubblegum/collection_verification.rs, nft_ingester/src/program_transformers/bubblegum/creator_verification.rs, nft_ingester/src/program_transformers/bubblegum/db.rs, nft_ingester/src/program_transformers/bubblegum/delegate.rs, nft_ingester/src/program_transformers/bubblegum/mod.rs, nft_ingester/src/program_transformers/bubblegum/redeem.rs, nft_ingester/src/program_transformers/bubblegum/transfer.rs, tools/txn_forwarder/README.md
fixes redeem txns from helius branch
=> Helius redeem txn

das_api/src/api/api_impl.rs, digital_asset_types/src/dapi/common/asset.rs, digital_asset_types/tests/data/infinite_fungi.json, digital_asset_types/tests/data/mad_lad.json, digital_asset_types/tests/json_parsing.rs, migration/src/m20230508_142103_add_offchain_reindex.rs, migration/src/m20230510_224316_cl_audit_table.rs
upstreaming another api change from helius
=> feat: add animation and image url to links

Cargo.lock, nft_ingester/Cargo.toml, nft_ingester/src/account_updates.rs, nft_ingester/src/backfiller.rs, nft_ingester/src/main.rs, nft_ingester/src/transaction_notifications.rs, tools/acc_forwarder/Cargo.toml, tools/acc_forwarder/src/main.rs, tools/txn_forwarder/Cargo.toml, tools/txn_forwarder/src/main.rs
Moves to use a backfill queue in redis for our tools and backfiller.
=> Change backfill queue

Cargo.lock, Cargo.toml, nft_ingester/src/program_transformers/bubblegum/collection_verification.rs, nft_ingester/src/program_transformers/bubblegum/mod.rs
fix for collection hash indexing from helius
=> fix: collection hash indexing (#104)

Cargo.lock, tree_backfiller/Cargo.toml, tree_backfiller/src/backfiller.rs, tree_backfiller/src/main.rs, tree_backfiller/src/rpc.rs, tree_backfiller/src/tree.rs
- Add retry and backoff to all rpc calls
=> Retry RPC Calls

das_api/src/config.rs, das_api/src/main.rs
- Configure max request connections on api server
=> Max Request Connections

nft_ingester/src/program_transformers/token_metadata/v1_asset.rs
Reverts rpcpool/digital-asset-rpc-infrastructure#135
=> Revert "No retries when looking up owner and token"

backfill/src/worker/tree.rs, blockbuster/src/lib.rs, tools/acc_forwarder/src/main.rs
* feat: allows complete reindex
* chore: allow deprecated borsh package
=> Add force flag to TreeWorkerArgs for complete reindexing (#148)

backfill/src/worker/program_transformer.rs, backfill/src/worker/transaction.rs
- Order transaction by slot instead of block_time
=> Order Bubblegum Backfill Transactions with Slot

backfill/src/lib.rs
- Replay only works on 1 tree at a time
- Optionally provide seq to backfill just them
=> Optional Seq Bubblegum Replay

docker-compose.yaml, grpc-ingest/config-grpc2redis.yml, grpc-ingest/src/config.rs, grpc-ingest/src/grpc.rs, grpc-ingest/src/prom.rs, grpc-ingest/src/redis.rs, prometheus-config.yaml
The size checks are async so when flush by max size get spawn to the flush handler.
- Switch to only time based flushes
- Rename prom metrics to follow promql conventions
- Add prom metric explorer to dev
=> Only Time Based Flushes

grpc-ingest/src/ingester.rs, grpc-ingest/src/redis.rs
- Drop using topograph on ingest command to test if it is causing performance issues
=> Remove Topograph from Ingest Command

Cargo.lock, core/src/solana_rpc.rs, ops/Cargo.toml, ops/src/account/cmd.rs, ops/src/account/mod.rs, ops/src/account/nft.rs
=> Add single NFT fetch and  backfill feature to ops 

grpc-ingest/config-grpc2redis.yml, grpc-ingest/config-ingester.yml, grpc-ingest/config-monitor.yml
=> Add comments to config files in grpc-ingest 

Cargo.lock, Cargo.toml, README.md, docker-compose.yaml, grpc-ingest/Cargo.toml, grpc-ingest/README.md, grpc-ingest/config-grpc2redis.yml, grpc-ingest/config-ingester.yml, grpc-ingest/config-monitor.yml, grpc-ingest/src/config.rs, grpc-ingest/src/grpc.rs, grpc-ingest/src/ingester.rs, grpc-ingest/src/prom.rs, grpc-ingest/src/redis.rs, ops/README.md, ops/src/account/cmd.rs
=> Separate global stream to multiple Program separated streams and handle each stream 

program_transformers/src/lib.rs
Currently the program transform takes out a single connection when its constructed and reuses that for the duration of the process. 
Switch to saving pgpool on the program transformer and then take out a connection for handling each event.
=> Save pgpool on program transformer and take out connection on handler

program_transformers/src/token_metadata/v1_asset.rs
=> Patch condition check on asset_grouping

program_transformers/src/token_metadata/v1_asset.rs
Reverts rpcpool/digital-asset-rpc-infrastructure#188
=> Revert "Patch condition check on asset_grouping"

program_transformers/src/asset_upserts.rs, program_transformers/src/token/mod.rs, program_transformers/src/token_metadata/master_edition.rs, program_transformers/src/token_metadata/v1_asset.rs
Reverts rpcpool/digital-asset-rpc-infrastructure#187
=> Revert "Only update the record when fields have changed for token and metadata programs"

blockbuster/src/instruction.rs, blockbuster/src/programs/token_extensions/extension.rs, core/src/metadata_json.rs, digital_asset_types/src/rpc/response.rs, grpc-ingest/src/redis.rs, metadata_json/src/worker.rs, nft_ingester/src/plerkle.rs, rust-toolchain.toml, tools/txn_forwarder/src/lib.rs
change rust version from 1.79 to 1.83 as tests are not building
=> update rust version to 1.83 for building tests

Api.Dockerfile, Builder.Dockerfile, Ingest.Dockerfile, Load.Dockerfile, Migrator.Dockerfile, Proxy.Dockerfile, digital_asset_types/src/dapi/change_logs.rs, digital_asset_types/tests/common.rs, grpc-ingest/src/config.rs, grpc-ingest/src/prom.rs, grpc-ingest/src/redis.rs, nft_ingester/src/backfiller.rs, program_transformers/src/bubblegum/db.rs, rust-toolchain.toml
Add metrics to track metadata json download
=> Add metrics to track metadata_json_download success and failure

grpc-ingest/config-grpc2redis.example.yml, grpc-ingest/src/config.rs, grpc-ingest/src/grpc.rs
- Each subscription can boot multiple pipelines to handle more load.
=> Use multiple pipelines per subscription

Cargo.lock, core/src/metadata_json.rs, docker-compose.yaml, grpc-ingest/config-ingester.example.yml, ops/Cargo.toml, ops/src/main.rs, ops/src/metadata/backfiller.rs, ops/src/metadata/cmd.rs, ops/src/metadata/mod.rs
Add metadata json backfiller to periodically backfill metdata json which are marked as processing
=> Das 106 add metadata json backfiller to das

das_api/src/main.rs
set RUST_LOG=das_api=warn which logs error responses
=> add prod error logging for error responses

das_api/src/api/api_impl.rs, das_api/src/api/mod.rs, digital_asset_types/src/dao/scopes/asset.rs, digital_asset_types/src/rpc/asset.rs, integration_tests/tests/integration_tests/snapshots/integration_tests__token_accounts_tests__get_token_largest_accounts.snap
- Need to return results in value field and add context with slot as 0
=> Respond with solana response context

digital_asset_types/src/rpc/filter.rs, integration_tests/tests/integration_tests/token_type_test.rs
- Adjust names of token type values to match other providers
https://docs.helius.dev/compression-and-das-api/digital-asset-standard-das-api/fungible-token-extension#how-does-it-work
=> Adjust token type values to match DAS API spec

integration_tests/tests/integration_tests/snapshots/integration_tests__fungibles_and_token_extensions_tests__token_extensions_get_asset_scenario_1.snap, program_transformers/src/asset_upserts.rs
- Update specification version on mint
=> Set Specification Version on Mint Update

program_transformers/src/token_extensions/mod.rs
- On token extensions TA accounts only try to write the owner if the amount is 1. Asset only tracks ownership on NFTs which have an amount of 1.
=> Only Update Ownership On TA Amount of 1
